### PR TITLE
Fix some suboptimal patterns identified by lintr

### PR DESCRIPTION
**Pull request by Bisaloo**
One potential last thing is that `find_compress()` could use the `endsWith()` base R function:

https://github.com/gesistsa/rio/blob/588971f7c5558805c1e7efc2f89cc0e1f245a4c7/R/compression.R#L1-L35

But from my (admittedly limited) testing, it seems that `NA_character_` is a possible value for `f`, leading to the creation of a file named `NA`. This means `endsWith()` is not a good fit here.

But is it an explicit design choice to allow `NA_character_` or an unexpected side effect?

### CODE REVIEW

**Comment by Bisaloo** [comment]
Tests failures are due to https://github.com/r-lib/testthat/issues/1969.

**Comment by chainsawriot** [comment]
@Bisaloo Once again, thank you very much for the PR. Most of them LGTM. I still have to actually stress test the removal of the `setwd()`. Those code is not automatically checked and last time I checked, `setwd()` must still be there. #319

**Comment by chainsawriot** [comment]
For this, `NA_character_` is surely an unexpected side effect and should be excluded. So, I think it's safe to use `endsWith()` here. I will open another issue related to this.

> One potential last thing is that `find_compress()` could use the `endsWith()` base R function:
> 
> https://github.com/gesistsa/rio/blob/588971f7c5558805c1e7efc2f89cc0e1f245a4c7/R/compression.R#L1-L35
> 
> But from my (admittedly limited) testing, it seems that `NA_character_` is a possible value for `f`, leading to the creation of a file named `NA`. This means `endsWith()` is not a good fit here.
> 
> But is it an explicit design choice to allow `NA_character_` or an unexpected side effect?

**Comment by chainsawriot** [comment]
> @Bisaloo Once again, thank you very much for the PR. Most of them LGTM. I still have to actually stress test the removal of the `setwd()`. Those code is not automatically checked and last time I checked, `setwd()` must still be there. #319

OK, This one should be fine.

**Comment by chainsawriot** [comment]
@Bisaloo Please add yourself to `Authors@R`. Then I will merge this.

**Pull request merged**
